name: Frontend CD

on:
    workflow_run:
        workflows: ["Frontend CI"]
        types:
            - completed

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Download Build Artifact
              uses: actions/download-artifact@v4
              with:
                  name: Build
                  path: /home/ec2-user/test
