name: Frontend CI

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install Dependencies
              run: yarn install

            - name: Build Vite Artifacts
              run: npm run build

            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: Build
                  path: ./dist
                  retention-days: 1
